#!/usr/bin/env bash

set -Eeuo pipefail

APP_DIR="${APP_DIR:-/home/tamliteco/luxquote.app}"
BACKUP_DIR="${BACKUP_DIR:-$APP_DIR/backups}"
MANIFEST="${MANIFEST:-$BACKUP_DIR/deploy-manifest-latest.env}"
WITH_DATABASE=false
ASSUME_YES=false
TARGET_COMMIT="${ROLLBACK_COMMIT:-}"
BACKUP_FILE="${ROLLBACK_BACKUP:-}"

usage() {
    cat <<'EOF'
Usage:
  bash scripts/rollback-production.sh [options]

Options:
  --code-only             Roll back code only. This is the default.
  --with-database         Also restore the pre-deploy database backup from the manifest.
  --yes                   Skip the interactive database restore confirmation.
  --manifest PATH         Use a specific deploy manifest. Useful after a failed deploy:
                          backups/deploy-manifest-pending.env
  --commit SHA            Roll back to a specific commit instead of PREVIOUS_COMMIT.
  --backup PATH           Use a specific database backup with --with-database.
  --help                  Show this help.

Notes:
  - This script never removes or prunes Docker volumes.
  - Database restore is destructive and only runs with --with-database.
EOF
}

timestamp() {
    date +"%Y-%m-%d %H:%M:%S"
}

log() {
    printf '[%s] %s\n' "$(timestamp)" "$*"
}

while [ "$#" -gt 0 ]; do
    case "$1" in
        --code-only)
            WITH_DATABASE=false
            ;;
        --with-database)
            WITH_DATABASE=true
            ;;
        --yes)
            ASSUME_YES=true
            ;;
        --manifest)
            MANIFEST="${2:-}"
            shift
            ;;
        --commit)
            TARGET_COMMIT="${2:-}"
            shift
            ;;
        --backup)
            BACKUP_FILE="${2:-}"
            shift
            ;;
        --help|-h)
            usage
            exit 0
            ;;
        *)
            log "ERROR: Unknown option: $1"
            usage
            exit 1
            ;;
    esac

    shift
done

if [ ! -f "$MANIFEST" ]; then
    log "ERROR: Rollback manifest not found: $MANIFEST"
    log "Expected the latest successful deploy manifest at backups/deploy-manifest-latest.env."
    log "If the last deploy failed before completion, try --manifest backups/deploy-manifest-pending.env."
    exit 1
fi

# The manifest is generated by scripts/deploy-production.sh and stored on the server.
# shellcheck disable=SC1090
source "$MANIFEST"

APP_DIR="${APP_DIR:-/home/tamliteco/luxquote.app}"
BACKUP_DIR="${BACKUP_DIR:-$APP_DIR/backups}"
DEPLOY_BRANCH="${DEPLOY_BRANCH:-production}"
PUBLIC_URL="${PUBLIC_URL:-https://quote.tamlite.co.uk}"
TARGET_COMMIT="${TARGET_COMMIT:-${PREVIOUS_COMMIT:-}}"
BACKUP_FILE="${BACKUP_FILE:-${FULL_BACKUP:-}}"
rollback_timestamp="$(date +%Y%m%d-%H%M%S)"
rollback_record="$BACKUP_DIR/rollback-${rollback_timestamp}.env"
rollback_latest="$BACKUP_DIR/rollback-latest.env"

if [ -z "$TARGET_COMMIT" ]; then
    log "ERROR: No rollback commit was provided and PREVIOUS_COMMIT is missing from $MANIFEST."
    exit 1
fi

if [ ! -d "$APP_DIR/.git" ]; then
    log "ERROR: $APP_DIR is not a git checkout."
    exit 1
fi

if [ "$WITH_DATABASE" = true ] && [ ! -s "$BACKUP_FILE" ]; then
    log "ERROR: Database rollback requested but backup was not found or is empty: $BACKUP_FILE"
    exit 1
fi

env_value() {
    if [ -f .env ]; then
        awk -F= -v key="$1" '$1 == key { print substr($0, index($0, "=") + 1); exit }' .env \
            | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//"
    fi
}

confirm_database_restore() {
    local answer

    if [ "$WITH_DATABASE" != true ] || [ "$ASSUME_YES" = true ]; then
        return
    fi

    cat <<EOF

WARNING: You requested a database rollback.

This will overwrite the production database using:
  $BACKUP_FILE

Type RESTORE to continue:
EOF

    read -r answer

    if [ "$answer" != "RESTORE" ]; then
        log "Database restore was not confirmed. Aborting before any rollback work."
        exit 1
    fi
}

write_rollback_record() {
    local path="$1"

    : > "$path"
    printf 'ROLLED_BACK_AT=%q\n' "$(timestamp)" >> "$path"
    printf 'APP_DIR=%q\n' "$APP_DIR" >> "$path"
    printf 'DEPLOY_BRANCH=%q\n' "$DEPLOY_BRANCH" >> "$path"
    printf 'PUBLIC_URL=%q\n' "$PUBLIC_URL" >> "$path"
    printf 'SOURCE_MANIFEST=%q\n' "$MANIFEST" >> "$path"
    printf 'TARGET_COMMIT=%q\n' "$TARGET_COMMIT" >> "$path"
    printf 'DATABASE_RESTORED=%q\n' "$WITH_DATABASE" >> "$path"
    printf 'DATABASE_BACKUP=%q\n' "$BACKUP_FILE" >> "$path"
}

cd "$APP_DIR"
mkdir -p "$BACKUP_DIR"

confirm_database_restore

log "Marking production checkout as a safe git directory"
git config --global --add safe.directory "$APP_DIR"

log "Starting production rollback to commit: $TARGET_COMMIT"
log "Using manifest: $MANIFEST"

log "Checking Docker services"
docker compose up -d

log "Fetching git history for $DEPLOY_BRANCH"
git fetch origin "$DEPLOY_BRANCH"

if ! git cat-file -e "${TARGET_COMMIT}^{commit}" 2>/dev/null; then
    log "ERROR: Target commit is not available locally after fetch: $TARGET_COMMIT"
    exit 1
fi

log "Checking out rollback commit"
git checkout --force "$TARGET_COMMIT"

log "Building and starting Docker services"
docker compose up -d --build

log "Removing local-only Vite dev marker"
rm -f public/hot

log "Ensuring container file ownership"
docker compose exec laravel.test chown -R sail:sail /var/www/html
docker compose exec laravel.test rm -rf /var/www/html/node_modules/.vite-temp
docker compose exec laravel.test sh -lc 'mkdir -p /var/www/html/storage/app/browsershot /home/sail/.cache/puppeteer && chown -R sail:sail /var/www/html/storage/app/browsershot /home/sail/.cache'

log "Installing Composer dependencies without framework scripts"
docker compose exec laravel.test composer install --no-dev --optimize-autoloader --no-interaction --no-scripts

log "Installing npm dependencies and building assets"
docker compose exec -u sail laravel.test npm install
docker compose exec -u sail laravel.test npx puppeteer browsers install chrome-headless-shell
docker compose exec -u sail laravel.test npm run build

log "Completing Composer autoload and framework discovery"
docker compose exec laravel.test composer dump-autoload --optimize

if [ "$WITH_DATABASE" = true ]; then
    DB_DATABASE="${DB_DATABASE:-$(env_value DB_DATABASE)}"
    DB_USERNAME="${DB_USERNAME:-$(env_value DB_USERNAME)}"
    DB_PASSWORD="${DB_PASSWORD:-$(env_value DB_PASSWORD)}"
    DB_DATABASE="${DB_DATABASE:-laravel}"
    DB_USERNAME="${DB_USERNAME:-sail}"
    DB_PASSWORD="${DB_PASSWORD:-password}"

    log "Restoring production database from: $BACKUP_FILE"
    if ! gzip -dc "$BACKUP_FILE" | docker compose exec -T mysql mysql -u "$DB_USERNAME" -p"$DB_PASSWORD" "$DB_DATABASE"; then
        log "ERROR: Database restore failed."
        log "The code rollback has already checked out $TARGET_COMMIT, but the database restore did not complete."
        log "Check that the backup is a valid gzipped MySQL dump and that it contains DROP TABLE statements for a full restore."
        exit 1
    fi
fi

log "Restarting app container"
docker compose restart laravel.test

log "Clearing and rebuilding Laravel caches"
docker compose exec laravel.test php artisan optimize:clear
docker compose exec laravel.test php artisan config:cache
docker compose exec laravel.test php artisan route:cache
docker compose exec laravel.test php artisan view:cache

log "Smoke checking $PUBLIC_URL"
curl --fail --silent --show-error --location --max-time 20 "$PUBLIC_URL" >/dev/null

log "Writing rollback record"
write_rollback_record "$rollback_record"
cp "$rollback_record" "$rollback_latest"

log "Production rollback complete"
